"""
Stage 4: Feature Engineering
============================
Amazon ML Challenge - Business Entity Resolution

Reads the candidate pairs generated by Stage 3 (Blocking).
Loads the preprocessed Parquet data from Stage 2.
Computes string similarity features (Levenshtein, Jaro-Winkler, Token Sort) using RapidFuzz.
Dumps the final feature dataframes as Parquet files ready for ML training.
"""

import os
import sys
import gc
import time
import pandas as pd
import numpy as np
from pathlib import Path
from rapidfuzz import fuzz, distance as rf_dist
from tqdm import tqdm

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
PROCESSED_DIR = PROJECT_ROOT / "output" / "processed"
OUTPUT_DIR = PROJECT_ROOT / "output"

def load_preprocessed_data(is_test=False):
    """Load the preprocessed Parquet data."""
    prefix = "test" if is_test else "train"
    print(f"Loading preprocessed {prefix} data dictionaries...")
    
    df1 = pd.read_parquet(PROCESSED_DIR / f"{prefix}_source1_cleaned.parquet")
    df2 = pd.read_parquet(PROCESSED_DIR / f"{prefix}_source2_cleaned.parquet")
    df3 = pd.read_parquet(PROCESSED_DIR / f"{prefix}_source3_cleaned.parquet")
    
    # Combine S2 and S3 for easy lookup
    targets = pd.concat([df2, df3], ignore_index=True)
    
    # Create dict lookups for fast O(1) access
    s1_dict = df1.set_index('entity_id')[['name_norm', 'address_norm', 'pincode', 'country_norm']].to_dict('index')
    tgt_dict = targets.set_index('entity_id')[['name_norm', 'address_norm', 'pincode', 'country_norm']].to_dict('index')
    
    del df1, df2, df3, targets
    gc.collect()
    
    return s1_dict, tgt_dict

def load_candidate_pairs(is_test=False):
    """Load the candidate pairs TSV and expand into a flat list of pairs."""
    filename = "test_candidate_pairs.tsv" if is_test else "train_candidate_pairs.tsv"
    filepath = OUTPUT_DIR / filename
    
    print(f"Loading candidate pairs from {filepath}...")
    if not filepath.exists():
        print(f"Error: {filepath} not found. Run Stage 3 first.")
        sys.exit(1)
        
    df = pd.read_csv(filepath, sep="\t", dtype=str, keep_default_na=False)
    
    # Expand the comma-separated candidate IDs into a flat list of (s1_id, cand_id)
    pairs = []
    for row in df.itertuples(index=False):
        s1 = row.source1_entity_id
        cands = str(row.candidate_entity_ids).split(',')
        for c in cands:
            c = c.strip()
            if c:
                pairs.append((s1, c))
                
    print(f"Loaded {len(pairs):,} individual candidate pairs to score.")
    return pairs

def compute_features(s1_dict, tgt_dict, pairs):
    """
    Compute pairwise features using RapidFuzz.
    """
    features = []
    
    for s1_id, cand_id in tqdm(pairs, desc="Extracting features"):
        s1 = s1_dict.get(s1_id, {})
        tgt = tgt_dict.get(cand_id, {})
        
        # Strings
        n1 = s1.get('name_norm', '')
        n2 = tgt.get('name_norm', '')
        a1 = s1.get('address_norm', '')
        a2 = tgt.get('address_norm', '')
        p1 = s1.get('pincode', '')
        p2 = tgt.get('pincode', '')
        c1 = s1.get('country_norm', '')
        c2 = tgt.get('country_norm', '')
        
        # Base string lengths
        len_n1 = len(n1)
        len_n2 = len(n2)
        len_a1 = len(a1)
        len_a2 = len(a2)
        
        # Feature computation
        f = {
            's1_id': s1_id,
            'cand_id': cand_id,
            
            # Name Features
            'name_lev_ratio': fuzz.ratio(n1, n2) / 100.0 if n1 and n2 else 0.0,
            'name_jaro_winkler': rf_dist.JaroWinkler.normalized_similarity(n1, n2) if n1 and n2 else 0.0,
            'name_token_sort': fuzz.token_sort_ratio(n1, n2) / 100.0 if n1 and n2 else 0.0,
            'name_token_set': fuzz.token_set_ratio(n1, n2) / 100.0 if n1 and n2 else 0.0,
            'name_len_diff': abs(len_n1 - len_n2),
            'name_len_min': min(len_n1, len_n2),
            'name_len_max': max(len_n1, len_n2),
            
            # Address Features
            'addr_lev_ratio': fuzz.ratio(a1, a2) / 100.0 if a1 and a2 else 0.0,
            'addr_jaro_winkler': rf_dist.JaroWinkler.normalized_similarity(a1, a2) if a1 and a2 else 0.0,
            'addr_token_sort': fuzz.token_sort_ratio(a1, a2) / 100.0 if a1 and a2 else 0.0,
            'addr_token_set': fuzz.token_set_ratio(a1, a2) / 100.0 if a1 and a2 else 0.0,
            'addr_len_diff': abs(len_a1 - len_a2),
            'addr_len_min': min(len_a1, len_a2),
            'addr_len_max': max(len_a1, len_a2),
            
            # Metadata Matches
            'pincode_match': 1 if p1 and p2 and p1 == p2 else 0,
            'country_match': 1 if c1 and c2 and c1 == c2 else 0,
            
            # Target Source indicator (S2 or S3)
            'is_s2': 1 if cand_id.startswith('S2-') else 0,
        }
        features.append(f)
        
    return pd.DataFrame(features)

def process_features(is_test=False):
    prefix = "test" if is_test else "train"
    print(f"\n--- RUNNING STAGE 4 ON {prefix.upper()} SET ---")
    t0 = time.time()
    
    # Load candidate pairs
    pairs = load_candidate_pairs(is_test)
    
    if not pairs:
        print("No pairs found. Exiting.")
        return
        
    # Load preprocessed lookup dictionaries
    s1_dict, tgt_dict = load_preprocessed_data(is_test)
    
    # Compute features
    features_df = compute_features(s1_dict, tgt_dict, pairs)
    
    # Save to disk as highly optimized parquet
    out_file = PROCESSED_DIR / f"{prefix}_features.parquet"
    print(f"\nSaving {len(features_df):,} feature vectors to {out_file}...")
    features_df.to_parquet(out_file, index=False)
    
    print(f"Done! Feature Engineering Time: {time.time() - t0:.1f}s")

if __name__ == "__main__":
    process_features(is_test=False)
    process_features(is_test=True)
