"""
Stage 4: Cross-Encoder Dataset Preparation
==========================================
Amazon ML Challenge - Business Entity Resolution

Takes the Top-K candidates generated by FAISS and maps them against the 
ground truth to create a binary classification dataset of (text_a, text_b, label).
This creates a dataset rich in "hard negatives" (items that are semantically 
similar but not matches) to train a highly discriminative Cross-Encoder.
"""

import sys
import gc
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
DATASET_DIR = PROJECT_ROOT / "dataset"
PROCESSED_DIR = PROJECT_ROOT / "output" / "processed"
OUTPUT_DIR = PROJECT_ROOT / "output"

def load_preprocessed_texts():
    print("Loading preprocessed text dictionaries...")
    df1 = pd.read_parquet(PROCESSED_DIR / "train_source1_cleaned.parquet")
    df2 = pd.read_parquet(PROCESSED_DIR / "train_source2_cleaned.parquet")
    df3 = pd.read_parquet(PROCESSED_DIR / "train_source3_cleaned.parquet")
    
    # We will feed the cross encoder the raw concatenated string
    df1['ce_text'] = df1['business_name'] + " " + df1['business_address'] + " " + df1['country']
    df2['ce_text'] = df2['business_name'] + " " + df2['business_address'] + " " + df2['country']
    df3['ce_text'] = df3['business_name'] + " " + df3['business_address'] + " " + df3['country']
    
    s1_dict = df1.set_index('entity_id')['ce_text'].to_dict()
    
    targets = pd.concat([df2, df3], ignore_index=True)
    tgt_dict = targets.set_index('entity_id')['ce_text'].to_dict()
    
    del df1, df2, df3, targets
    gc.collect()
    return s1_dict, tgt_dict

def prepare_dataset():
    s1_dict, tgt_dict = load_preprocessed_texts()
    
    print("Loading FAISS candidates...")
    cands_path = OUTPUT_DIR / "train_candidate_pairs.tsv"
    if not cands_path.exists():
        print(f"Error: {cands_path} not found. Run Stage 3 first.")
        sys.exit(1)
        
    cands_df = pd.read_csv(cands_path, sep="\t", dtype=str, keep_default_na=False)
    
    print("Loading Ground Truth...")
    gt_df = pd.read_csv(DATASET_DIR / "train" / "train_ground_truth.tsv", sep="\t", dtype=str, keep_default_na=False)
    gt_map = {}
    for _, row in gt_df.iterrows():
        gt_map[row['source1_entity_id']] = set([m.strip() for m in str(row['matched_entity_ids']).split(',') if m.strip()])
        
    print("Building (text_a, text_b, label) pairs...")
    dataset = []
    
    for row in cands_df.itertuples(index=False):
        s1 = row.source1_entity_id
        cands = [c.strip() for c in str(row.candidate_entity_ids).split(',') if c.strip()]
        
        true_matches = gt_map.get(s1, set())
        
        for cand in cands:
            label = 1.0 if cand in true_matches else 0.0
            
            text_a = s1_dict.get(s1, "")
            text_b = tgt_dict.get(cand, "")
            
            if text_a and text_b:
                dataset.append({
                    'text_a': text_a,
                    'text_b': text_b,
                    'label': label
                })
                
    final_df = pd.DataFrame(dataset)
    print(f"Dataset compiled: {len(final_df):,} total pairs.")
    print(f"Positives: {final_df['label'].sum():,} | Negatives: {len(final_df) - final_df['label'].sum():,}")
    
    out_file = PROCESSED_DIR / "cross_encoder_train.parquet"
    final_df.to_parquet(out_file, index=False)
    print(f"Saved dataset to {out_file}")

if __name__ == "__main__":
    prepare_dataset()
